# Generated by Django 4.1.2 on 2022-11-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0002_alter_user_direction_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
