# Generated by Django 4.1.2 on 2022-11-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0004_author_category_order_product_productentry_opinion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='collection',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
