# Generated by Django 4.1.2 on 2022-11-08 18:25

import acme_nft_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0005_rename_authors_product_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='rarity',
            field=models.CharField(choices=[(acme_nft_app.models.RarityType['common'], 'COMMON'), (acme_nft_app.models.RarityType['rare'], 'RARE'), (acme_nft_app.models.RarityType['epic'], 'EPIC'), (acme_nft_app.models.RarityType['legendary'], 'LEGENDARY'), (acme_nft_app.models.RarityType['mythic'], 'MYTHIC')], default=acme_nft_app.models.RarityType['common'], max_length=60),
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acme_nft_app.author'),
        ),
    ]
