# Generated by Django 4.1.2 on 2022-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0006_remove_product_category_product_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
