# Generated by Django 4.1.2 on 2022-11-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0007_alter_opinion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acme_nft_app.user'),
        ),
    ]
