# Generated by Django 4.1.2 on 2022-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme_nft_app', '0009_alter_opinion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme_nft_app.user'),
        ),
    ]
