version: "3.8"

networks:
  acme_nft:
    name: acme_nft
    driver: bridge
services:
  web:
    container_name: acme_nft_web
    image: acme_nft_web:latest
    build: .
    restart: always
    command: ash -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py initAdmin && 
                     python manage.py populateDB &&
                     gunicorn -w 5 acme_nft.wsgi --timeout=500 -b 0.0.0.0:5000"
    expose:
      - "5000"
    volumes:
      - static:/Acme-NFT/acme_nft/static

    environment:
      DATABASE_URL: postgres://acme:acme@db:5432/acme_nft_db
      POSTGRES_DB: acme_nft_db
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme

    depends_on:
      - db
      - redis

    links:
      - db
      - redis

    networks:
      - acme_nft

  db:

    restart: always

    container_name: acme_nft_db

    image: postgres:alpine

    ports:
        - "5432:5432"

    volumes:

      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: acme_nft_db
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme
    
    networks:
      - acme_nft

  redis:
    container_name: acme_nft_redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - acme_nft

  # nginx:
  #     container_name: acme_nft_nginx
  #     restart: always
  #     image: acme_nft_nginx:latest
  #     ports:
  #       - "8000:80"
  #     build:
  #       context: .
  #       dockerfile: Dockerfile-nginx
  #     volumes:
  #       - static:/Acme-NFT/acme_nft/static
  #     depends_on:
  #       - web
  #     networks:
  #       - acme_nft

volumes:
  static:
    name: acme_nft_static

  db:
    name: acme_nft_db